### ISSUE TITLE
Not loading my Dockerfile

### ISSUE THREAD

**Issue by nalipaz** [hassio-addons/build-env#36]
# Problem/Motivation

> Trying to use this image to build my addon, but it doesn't find my Dockerfile

## Expected behavior

> It will find my Dockerfile as outlined in the docs

## Actual behavior

> An error suggesting I might be missing my Dockerfile

## Steps to reproduce

> Build my project from my repository at https://github.com/nalipaz/hassio-addons

## Proposed changes

> Better documentation or perhaps an example that works on shippable?

Here is my output from my shippable job that fails:
https://app.shippable.com/github/nalipaz/hassio-addons/runs/91/1/console

If you look at my [shippable.yml](https://github.com/nalipaz/hassio-addons/blob/master/shippable.yml) it might give some insight as to how I am building and what might need to change. I have output some `ls` functions to show the files are there but don't seem to be found by the image.

**Comment by frenck** [comment]
You are mounting `/docker` -> `/docker`, instead of the shippable  `${SHIPPABLE_BUILD_DIR}`.

Maybe try: `docker run --rm --privileged -v ${SHIPPABLE_BUILD_DIR}:/docker -v /root/.docker:/root/.docker hassioaddons/build-env:latest --target ${ADDON} --tag-latest --push --${ARCH}`

Check out my CircleCI configuration in the example addon: 
https://github.com/hassio-addons/addon-example/blob/master/.circleci/config.yml

**Comment by nalipaz** [comment]
@frenck I know my example shows me mounting /docker:/docker but I have tried every permutation I can think of. As an example: https://app.shippable.com/github/nalipaz/hassio-addons/runs/92/1/console which does your suggestion, and you are welcome to look at any of the builds I ran after that as they all try variations on the directory.

**Comment by frenck** [comment]
I'm not sure what is wrong there (I do not have any experience with Shippable).

I've tried building your add-on locally from the command line using this build environment; that failed. You're add-on actually made me discover a bug in the build environment, which I'm fixing right now.

Nevertheless, that bug is not the issue with shippable.

I would strongly advise you to try to building locally first in order to get to know the build environment, before implementing it on a CI system. (You'll need to wait for me to put out a new version, which I will do within an hour).

**Comment by nalipaz** [comment]
cool, well thank you for helping, testing, and fixing your image. I will give it a go locally and if running properly try it again on shippable, but if that doesn't work I can always try it on circleci since you have a working example of that. If I find the solution for this then maybe I can PR against your example addon to include shippable as an example too.

**Comment by frenck** [comment]
I currently do not have the time to implement and test more CI systems.
Shippable is definitely on my wishlist to provide an example for (and TravisCI), your addition is more than welcome 👍 

CircleCI actually works amazing for this kind of jobs.

**Comment by frenck** [comment]
We already discussed your issue on discord and solved most of your issues.
Therefore closing this issue.
